# Generated by Django 4.2.4 on 2023-09-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Date', models.DateTimeField()),
            ],
        ),
    ]
